
name: tp0
services:

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - ./server/config.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=1
      - FIRST_NAME=Santiago
      - LAST_NAME=Baez
      - DOCUMENT=17789107
      - BIRTH_DATE=1935-12-09
      - NUMBER=5985
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=2
      - FIRST_NAME=Tomas
      - LAST_NAME=Baez
      - DOCUMENT=11449060
      - BIRTH_DATE=1954-02-11
      - NUMBER=8919
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=3
      - FIRST_NAME=Tomas
      - LAST_NAME=Baez
      - DOCUMENT=17145311
      - BIRTH_DATE=2020-03-11
      - NUMBER=3832
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=4
      - FIRST_NAME=Santiago
      - LAST_NAME=Lombardo
      - DOCUMENT=41796772
      - BIRTH_DATE=1952-09-25
      - NUMBER=7884
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    volumes:
      - ./client/config.yaml:/config.yaml
    environment:
      - CLI_ID=5
      - FIRST_NAME=Micaela
      - LAST_NAME=Baez
      - DOCUMENT=44451499
      - BIRTH_DATE=2000-03-14
      - NUMBER=8256
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
